import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/_index.tsx"),
    route("modules/new", "routes/modules.new.tsx"),
    route("modules", "routes/modules.tsx"),
    route("modules/:moduleId", "routes/modules.$moduleId.tsx"),
    route("modules/:id/edit", "routes/modules.$id.edit.tsx"),
    route("blog", "routes/blog.tsx"),
    route("blog/:postId", "routes/blog.$postId.tsx"),
    route("blog/:id/edit", "routes/blog.$id.edit.tsx"),
    route("write", "routes/write.tsx"),
    route("profile", "routes/profile.tsx"),
    route("login", "routes/login.tsx"),
    route("logout", "routes/logout.tsx"),
    route("resources", "routes/resources.tsx"),
    route("api/articles", "routes/api.articles.ts"),
    route("api/articles/:slug", "routes/api.articles.$slug.ts"),
    route("api/modules", "routes/api.modules.ts"),
    route("api/modules/featured", "routes/api.modules.featured.ts"),
    route("api/modules/published", "routes/api.modules.published.ts"),
    route("api/modules/published/:slug", "routes/api.modules.published.$slug.ts"),
    route("api/profile/articles", "routes/api.profile.articles.ts"),
    route("api/profile/articles/:id", "routes/api.profile.articles.$id.ts"),
    route("api/profile/modules", "routes/api.profile.modules.ts"),
    route("api/profile/modules/:id", "routes/api.profile.modules.$id.ts"),
    route("api/resources", "routes/api.resources.ts"),
    route("api/resources/:id", "routes/api.resources.$id.ts"),
    route("api/weather", "routes/api.weather.ts"),
    route("auth/callback", "routes/auth.callback.tsx"),
    route("api/me", "routes/api.me.ts"),
] satisfies RouteConfig;